### ISSUE TITLE
Add fonts for enh-ruby-mode custom faces?

### ISSUE THREAD

**Issue by Trevoke** [niflheim-theme/emacs#5]
I love the theme! Unfortunately, some things like `=` and `"` are dark/black in Ruby when using enh-ruby-mode and almost impossible to read.
https://github.com/zenspider/enhanced-ruby-mode

**Comment by NicolasPetton** [comment]
I don't write much Ruby, but if you can provide a minimal file for which you experience the issue, I'll be happy to fix it!

**Comment by Trevoke** [comment]
Actually, after trying our your theme again now, it looks like my concerns have been taken care of already!

I'll play with your theme some more, thank you :)

**Comment by NicolasPetton** [comment]
Great then, closing this issue!
