### ISSUE TITLE
Colors in magit diff mode

### ISSUE THREAD

**Issue by jdahm** [niflheim-theme/emacs#6]
Thanks for putting together this theme. I've noticed that the red/green highlighting is disabled for the hunk at point when looking at magit diffs. It appears that the darkening background is disabling these colors.

This does not seem to be an issue simple diff-mode e.g. when looking at patches.

**Comment by NicolasPetton** [comment]
Can you try with `emacs -Q`? I don't have this issue:

![screenshot from 2015-04-29 10 10 59](https://cloud.githubusercontent.com/assets/123539/7386826/57a35d20-ee58-11e4-97ba-37a9614a7c66.png)

**Comment by jdahm** [comment]
Huh, you're right I don't have the issue in that case. I'll close this and continue tracking it down on my end.
